function makeSubplot(r, c, k)

addpath Utils2/SubAxis
subaxis(r, c, k, 'SpacingHoriz', 0.01, 'SpacingVert', 0, ...
    'PaddingRight', 0.02, 'PaddingLeft', 0.02, ...
    'PaddingTop', 0.0, 'PaddingBottom', 0.0, ...
    'MarginRight', 0.02, 'MarginLeft', 0.02, ...
    'MarginTop', 0.08, 'MarginBottom', 0.1);
rmpath Utils2/SubAxis

end